extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.8",
        import: ["@key"])

enum CatalogCategory {
  PHYSICAL
  DIGITAL
}

interface CatalogItem @key(fields: "id") {
  id: ID!
  name: String!
  description: String
  category: CatalogCategory!
}

type Product implements CatalogItem @key(fields: "id") {
  id: ID!
  name: String!
  description: String
  category: CatalogCategory!
  weightGrams: Int!
}

type DigitalProduct implements CatalogItem @key(fields: "id") {
  id: ID!
  name: String!
  description: String
  category: CatalogCategory!
  downloadFormat: String!
}

type Query {
  product(id: ID!): Product
  products: [Product!]!
  catalog: [CatalogItem!]!
}
