spring.application.name=sgl-products
server.port=8080
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoints.web.discovery.enabled=false
