spring.application.name=pricing-subgraph
server.port=8080
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
spring.graphql.websocket.path=/graphql
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoints.web.discovery.enabled=false
